### ISSUE TITLE
Curious as to why GPL was chosen?

### ISSUE THREAD

**Issue by thomasdsouza** [Cleveroad/slidingtutorial-android#1]
Very nice library. However, seems like choice of GPL would limit adoption.

**Comment by alexeypodolian** [comment]
Thanks for your interest to our library. We have changed the license form GPL to MID.

**Comment by thomasdsouza** [comment]
Awesome. I sincerely wish this library gets massive adoption. Thanks again for all your hard work!

**Comment by alexeypodolian** [comment]
Thanks for feedback. If you will have any questions, please contact us.
