### ISSUE TITLE
Add ability to set custom ViewPager indicator

### ISSUE THREAD

**Issue by Iojjj** [Cleveroad/slidingtutorial-android#10]

**Comment by davinctor** [comment]
You could easily customize the [TutorialPageIndicator](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/TutorialPageIndicator.java) via [IndicatorOptions](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/IndicatorOptions.java). Here's sample how do it:

``` java
public class CustomTutorialFragment extends TutorialSupportFragment {
    @Override
    protected TutorialOptions provideTutorialOptions() {
        return newTutorialOptionsBuilder(getContext())
                .setIndicatorOptions(IndicatorOptions.newBuilder(getContext())
                        .setElementSizeRes(R.dimen.indicator_size)
                        .setElementSpacingRes(R.dimen.indicator_spacing)
                        .setElementColorRes(android.R.color.darker_gray)
                        .setSelectedElementColor(android.R.color.white)
                        .setRenderer(Drawable.create(getContext()))
                        .build())
                // setup other configuration ...
                .build();
    }
}
```

Pay attention to the `.setRenderer(Drawable.create(getContext()))` line. You could provide your custom [Renderer](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/Renderer.java) implementation, for example (took from [sample](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/sample/src/main/java/com/cleveroad/slidingtutorial/sample/renderer/RhombusRenderer.java)):

``` java
public class RhombusRenderer implements Renderer {

    private static final float ANGLE_45 = 45f;

    public static RhombusRenderer create() {
        return new RhombusRenderer();
    }

    private RhombusRenderer() {
    }

    @Override
    public void draw(@NonNull Canvas canvas, @NonNull RectF elementBounds, @NonNull Paint paint, boolean isActive) {
        canvas.save();
        canvas.rotate(ANGLE_45, elementBounds.centerX(), elementBounds.centerY());
        canvas.drawRect(elementBounds, paint);
        canvas.restore();
    }
}
```
