### ISSUE TITLE
How to solve manifest merger failed

### ISSUE THREAD

**Issue by Andecy** [Cleveroad/slidingtutorial-android#12]
the error info :

> Error:Execution failed for task ':lib:processDebugAndroidTestManifest'.
>  java.lang.RuntimeException: Manifest merger failed : **Attribute application@label value=(@string/app_name) from [debug] AndroidManifest.xml:11:9-41
>     is also present at [com.cleveroad:slidingtutorial:0.9.4] AndroidManifest.xml:13:9-44 value=(@string/st_app_name).**
>     Suggestion: add 'tools:replace="android:label"' to <application> element at manifestMerger41941130476540702.xml:7:5-9:19 to override.

**but I had add tools:replace="android:label to my application tag**

**Comment by Iojjj** [comment]
Try to use `tools:node="replace"` instead.

**Comment by Andecy** [comment]
Yes，I try write it on application tag，but it doesn't work ...

**Comment by Iojjj** [comment]
you need to write it on apllication tag.

**Comment by Andecy** [comment]
eh..of course,sorry but application tag also doesn't work

**Comment by Andecy** [comment]
hello,tools:node="replace" doesn't work in application tag

**Comment by Iojjj** [comment]
I've checked v 0.9.4 and don't get any errors during manifest merging in sample app. I'm using Android Studio 2.1 Beta 3. Maybe you see errors because of an old Gradle pllugin.

Updated library to v 0.9.5. Removed application tag from library to prevent merging errors. You can try it once this version will be visible in maven repo.

**Comment by Andecy** [comment]
I am using Android Studio 2.1 Beta3 too,the new version(v 0.9.5) can not find in Maven

**Comment by Iojjj** [comment]
New version is now available. It takes some time for synchronizing repositories. Close this issue if there will be no problems with new version or leave a comment otherwise.
