### ISSUE TITLE
How listen end of slide show  ?

### ISSUE THREAD

**Issue by afaucogney** [Cleveroad/slidingtutorial-android#19]
I wonder how to listen the end of the slides-set. Is there any event, method to override ?
I want to close the activity when the slide is done !

**Comment by Iojjj** [comment]
Let's say you have a `TutorialActivity` where you display `TutorialFragment`.
1. Add fragment to back stack
   
   ``` JAVA
   getSupportFragmentManager().beginTransaction()
       .add(R.id.container, new CustomPresentationPagerFragment())
       .addToBackStack(null)
       .commit(); 
   ```
2. Add `FragmentManager.OnBackStackChangedListener`
   
   ``` JAVA
   getSupportFragmentManager().addOnBackStackChangedListener(new FragmentManager.OnBackStackChangedListener() {
       @Override
       public void onBackStackChanged() {
           // check if TutorialFragment is displayed
           boolean tutorialEnded = getSupportFragmentManager().findFragmentById(R.id.container) == null;
           // or
           // boolean tutorialEnded = getSupportFragmentManager().getBackStackEntryCount() == 0;
           if (tutorialEnded) {
               finish();
           }
       }
   });
   ```

**Comment by LeaderChange** [comment]
sorry  I don't understand what you mean .Assume that there are three pages, when sliding in the third page, how to jump other Activity?

**Comment by jackzhonglyy** [comment]
My English is poor,i try to give a simlpe answer.
If you want to listener listen the end of the slides-set,you should know the `onPageSelected` position.
The demo have the class that `CustomPresentationPagerFragment`, the class is extends SimplePagerFragment&PresentationPagerFragment&Fragment;
In the file `PresentationPagerFragment`, have the method 
`/**`
`* When last position will be reached then remove fragment from the screen.`
`*/`
`@Override`
`public void onPageSelected(int position) {`
`if (!isInfiniteScrollEnabled() && position == getPagesCount()) {`
`removeFragmentFromScreen();`
`}`
`}
`
so, if you want to listener the end of slide , you can override this method. 

But, you should know, the method
 `/**
     * Enable or disable infinite scroll. Default value is false.
     *
     * @return true to enable infinite scroll, false otherwise.
     */
    protected boolean isInfiniteScrollEnabled() {
        return false;
    }`
control the pager Enable or disable infinite scroll. so, if you want to close the activity when the slide is done, you don't need override the method, just keep false;

**Comment by davinctor** [comment]
Hi @afaucogney and @jackzhonglyy, thanks for your replies.

We added new features, one of them is adding [OnTutorialPageChangeListener](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/OnTutorialPageChangeListener.java). You can easily identify last tutorial page via check position: `if (position == TOTAL_PAGES - 1)`. Here's [sample](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/sample/src/main/java/com/cleveroad/slidingtutorial/sample/CustomTutorialFragment.java#L153) how to use it:

``` java
public class CustomTutorialFragment extends TutorialSupportFragment
        implements OnTutorialPageChangeListener {

    private static final String TAG = "CustomTutorialFragment";
    private static final int TOTAL_PAGES = 3;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addOnTutorialPageChangeListener(this);
    }

    // other methods

    @Override
    public void onPageChanged(int position) {
        Log.i(TAG, "onPageChanged: position = " + position);
        if (position == TOTAL_PAGES - 1) {
            Log.i(TAG, "Last tutorial page.");
            // Do smth...
        }
    }
}
```

**Comment by MissMyDearBear** [comment]
...
.setUseAutoRemoveTutorialFragment(true)
...
@davincto 
 @Override
    public void onPageChanged(int position) {
        if (position == TutorialSupportFragment.EMPTY_FRAGMENT_POSITION) {
            getActivity.startActivity(new Intent(getActivity,MainActivity.class));
            getActivity.finsh();
        }
    }
As above, I want skip to next activity and  finsh current activity.

I found a phenomenon that the current Activity before the jump will remove the Fragment leading to the page blank, and then jump to the other Activity, which does not look smooth
