### ISSUE TITLE
Remove last empty fragment

### ISSUE THREAD

**Issue by mathieudebrito** [Cleveroad/slidingtutorial-android#20]
Hi guys, 

First of all, thank you for this awesome lib !

 Just one question : how can I remove the empty fragment at the end of the scroll ?

Thanks

**Comment by davinctor** [comment]
Hi @mathieudebrito, thanks for your reply.

We added new features, one of them is customization the using [empty fragment](https://github.com/Cleveroad/SlidingTutorial-Android#auto-remove-tutorialfragment---scroll-from-last-tutorial-page-to-your-content). Here's [sample](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/sample/src/main/java/com/cleveroad/slidingtutorial/sample/CustomTutorialFragment.java#L136):

``` java
public class CustomTutorialFragment extends TutorialFragment
        implements OnTutorialPageChangeListener {

    @Override
    protected TutorialOptions provideTutorialOptions() {
        return newTutorialOptionsBuilder(getActivity())
                .setUseAutoRemoveTutorialFragment(true)
                // setup other configuration
                .build();
    }

}
```
