### ISSUE TITLE
Error layout_heightPercent

### ISSUE THREAD

**Issue by meeftah** [Cleveroad/slidingtutorial-android#21]
I've got errors:
No resource identifier found for attribute 'layout_heightPercent' in package 'xxx'

**Comment by davinctor** [comment]
@meeftah, If you are using xml layout from library sample (for example [this one](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/sample/src/main/res/layout/fragment_page_first.xml#L21)) you have to add dependency for percent layout into your **build.gradle**: `compile 'com.android.support:percent:23.3.0'`
If it isn't your problem, could you share your xml layout?

**Comment by Iojjj** [comment]
It seems this error related to inattentive copy/paste. Closed.
