### ISSUE TITLE
change fonts face and Skip button layout 

### ISSUE THREAD

**Issue by salehmosleh** [Cleveroad/slidingtutorial-android#24]
how to change fonts face and Skip button layout ?

**Comment by Iojjj** [comment]
Hi @salehmosleh,
1. Create your own XML layout for tutorial page. See our layout [here](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/res/layout/st_fragment_presentation.xml).
2. Extend your tutorial fragment from `TutorialFragment` or `TutorialSupportFragment`.
3. Override all [this getters](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/TutorialFragment.java#L182-L205) and provide proper resource IDs.
4. ....
5. Profit

**Comment by salehmosleh** [comment]
thank you @Iojjj .

**Comment by Iojjj** [comment]
Hi, @salehmosleh.

There were some issues mentioned in #25 that affects your issue. It's fixed now in v.1.0.3
