### ISSUE TITLE
Page indicator position

### ISSUE THREAD

**Issue by paul-ovchinnikov** [Cleveroad/slidingtutorial-android#25]
I didn't find an ability to place indicator on arbitrary place on screen. For example I need to put indicator to top of screen. Please add an ability of layout_gravity for indicators

**Comment by Iojjj** [comment]
Hi @paul-ovchinnikov,
1. Create your own XML layout for tutorial page. See our layout [here](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/res/layout/st_fragment_presentation.xml).
2. Extend your tutorial fragment from `TutorialFragment` or `TutorialSupportFragment`.
3. Override all [this getters](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/TutorialFragment.java#L182-L205) and provide proper resource IDs.
4. ....
5. Profit

**Comment by paul-ovchinnikov** [comment]
This approach doesn't work. TutorialFragment still trying to use original layout and don't use custom layout.
Also if TransormItem[] size is 0, I get IllegarlArgumentStateExcepton.
One more question is there ability to set another size for focused indicator?

**Comment by Iojjj** [comment]
1. Thanks for pointing on this issue. It appeared after refactoring. We'll fix it and release new version next week.
2. We're not supporting tutorials without transform items at this moment. If you need to display tutorial without transform items, you can easily do it on your own using `ViewPager` and `Fragment`s. If you don't have transform item on one or multiple pages of tutorial, you can pass single `TransformItem` item with shift coefficient set to zero. Pass any view id in page's layout as `viewResId`.
3. It's not supported out of box. You can implement you own `Renderer` and draw anything you like. `Renderer` will receive `elementBounds` parameter which represents a rectangle where you need to draw your indicator and a `Canvas` object. At this point you can set scale on canvas and enlarge indicator (when flag `isActive` equals `true`) or enlarge rectangle and use it for drawing indicator.

**Comment by Iojjj** [comment]
fixed in v.1.0.3
