### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by MissMyDearBear** [Cleveroad/slidingtutorial-android#29]
In my APP,I want go to next activity when selecting the last page .
This is my code: setUseAutoRemoveTutorialFragment(true)
I find the activity,include Tutirual,perform an empty page,rather than liking the skip click events.

**Comment by Iojjj** [comment]
Hi @MissMyDearBear,

as I understand, you want to automatically go to the next activity as soon as a user opens the last page of tutorial? I don't think it's a good user experience. User should be able to go to the next activity by pressing some button that will indicate he/she understood and completed tutorial.

If you still want to open next activity automatically, you need to set `setUseAutoRemoveTutorialFragment(true)` and override `onPageChanged` method in your `TutorialFragment` and do something like this:

``` JAVA
@Override
public void onPageChanged(int position) {
    if (position == TutorialFragment.EMPTY_FRAGMENT_POSITION) {
        final Intent intent = new Intent(getContext(), NextActivity.class);
        startActivity(intent);
        getActivity().finish();
    }
}
```

Let me know if this helps you.

**Comment by Iojjj** [comment]
I've checked [your comment](https://github.com/Cleveroad/SlidingTutorial-Android/issues/19#issuecomment-246237598). If you want a smooth transition from tutorial page to your content, then use single activity:

``` JAVA
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // ...
    if (savedInstanceState == null) {
        getSupportFragmentManager()
            .beginTransaction()
            // first add your content
            .add(R.id.fragment_container, ContentFragment.newInstance())
            // then add your tutorial
            .add(R.id.fragment_container, TutorialFragment.newInstance())
            .commit();
    }
    // ...
}
```

In this case when you set `setUseAutoRemoveTutorialFragment(...)` to `true`, you will get smooth transition from tutorial to content. Currently I don't see any option of smooth transition to the next activity.

**Comment by VishalDalve** [comment]
First of all Nice work...
I have one problem, How can i make fragment images Clickable? I want to change the fragment on click of any image aslo. For that do i have to modify "PageFragment.java" ?
Thanks you.

**Comment by Iojjj** [comment]
@MissMyDearBear 

reopen this ticket if you still have any questions related to it.
