### ISSUE TITLE
Provide in skip button click listener

### ISSUE THREAD

**Issue by dasheck0** [Cleveroad/slidingtutorial-android#3]
Hi,

first of all awesome and clean library. I really like it and I prefer it over other libraries due to the fact, that you provide fragments instead of activities. Anyway there is no possibility of listening to the skip button click. Usually you want your own code to run instead of all the fragments are removed. I have something in mind like

```
@Override onSkipClicked(View view) {
  //your custom code here
}
```

Thanks for any feedback on this.

Best regards 
dasheck

**Comment by Iojjj** [comment]
Hi there.

Thanks for your feedback. Currently you can set your own on click listener in your fragment that extends `PresentationPagerFragment`. Simply override `onViewCreated(...)` method, find skip button by id and override our click listener with your own. Example:

``` Java
@Override
public void onViewCreated(View view, Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    ...
    view.findViewById(getButtonSkipResId()).setOnClickListener(v -> onSkipButtonClicked());
}
```

We may provide separate method for such things in next release.

**Comment by dasheck0** [comment]
Thanks for your fast response. I already did this. But I find a dedicated listener as part of the API much cleaner. Can't wait for the next release.

**Comment by Iojjj** [comment]
v.0.9.2 released with `onSkipButtonClicked` method on board.
