### ISSUE TITLE
First of all Nice work... I have one problem, How can i make fragment images Clickable? I want to change the fragment on click of any image aslo. For that do i have to modify "PageFragment.java" ? Thank  you.

### ISSUE THREAD

**Issue by VishalDalve** [Cleveroad/slidingtutorial-android#30]
First of all Nice work...
I have one problem, How can i make fragment images Clickable? I want to change the fragment on click of any image aslo. For that do i have to modify "PageFragment.java" ?
Thanks you.

**Comment by Iojjj** [comment]
Hi, @WebsVentoVishal,

you need to use the first approach (extending from `PageFragment` or `PageSupportFragment`) described in **Readme** file. Than in your implementation of `PageFragment` or `PageSupportFragment` you can find your views and do whatever you want to do.

``` JAVA
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View view = /* inlfate you page's view */ ;
    ImageView myImage = (ImageView) view.findViewById(R.id.clickable_image);
    myImage.setOnClickListener(v -> /* do something on click */ );
    return view;
}
```

**Comment by VishalDalve** [comment]
Thanks for quick reply, this is done but main problem arise when i want to slide to 1st fragment from 3rd fragment on click of ...
As method given in viewPager "  mViewPager.setCurrentItem(position);
where position is the Fragment no. which will call from individual fragment.

**Comment by Iojjj** [comment]
I guess this is what you want:

``` JAVA
@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View view = /* inlfate you page's view */ ;
    ImageView myImage = (ImageView) view.findViewById(R.id.clickable_image);
    myImage.setOnClickListener(v -> {
        // pass an event to tutorial fragment in any way
        App.getBus().fireEvent(new OffsetEvent(-2)); // scroll back 2 fragments
    });
    return view;
}
```

For example, you can implement an Event Bus for passing events between fragments. Also you can just pass a reference to your tutorial fragment implementation into `PageFragment` or `PageSupportFragment` implementation but make sure you restore this reference on view state restoration (like rotation of device).

This event should contain an offset for scrolling, for example:

``` Java
public class OffsetEvent {
    private final int mOffset;

    public OffsetEvent(int offset) {
        mOffset = offset;
    }

    public int getOffset() {
        return mOffset;
    }
}
```

When your tutorial fragment get this event, you can do something like this:

``` Java
public void onEventHappened(@NonNull OffsetEvent event) {
    ViewPager viewPager = getViewPager();
    int curPos = viewPager .getCurrentItem();
    // offset can be negative to scroll back
    int newPos = curPos + event.getOffset();
    viewPager.setCurrentItem(newPos);
}
```

This should do the trick for both infinite scroll enabled and disabled options.

**Comment by Iojjj** [comment]
@WebsVentoVishal 

reopen this ticket if you still have a questions related to it.
