### ISSUE TITLE
ViewPager indicator not visible.

### ISSUE THREAD

**Issue by ghost** [Cleveroad/slidingtutorial-android#36]
Pager indicator not visible. Can you please help me to solve this issue.

**Comment by Iojjj** [comment]
Hi @SanVakil,

please provide more info:
- do you use default tutorial layout or custom one?
- if custom, provide your XML layout of tutorial screen (where you placed indicator and ViewPager)
- what is your phone's screen sizes and DPI?
- screenshot

**Comment by ghost** [comment]
Hi Lojjj,

I think DrawableRenderer is not visible .  when set background for TutorialPageIndicator layout it showed background color, but it not visible the Pager indicator circle image. I didn't changed anything in the DrawableRenderer class. Can you please help me to solve this issue.

Here I have mentioned my layout please review it.

# **custom_tutorial_layout.xml**

``` xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/background">

    <ImageView
        android:id="@+id/ic_logo"
        android:layout_marginBottom="@dimen/activity_horizontal_margin"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:contentDescription="@string/name"
        android:src="@drawable/ic_logo" />

    <FrameLayout
        android:id="@+id/tutorialView"
        android:layout_above="@+id/btn_continue"
        android:layout_below="@+id/ic_logo"
        android:layout_marginBottom="@dimen/activity_horizontal_margin"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <android.support.v4.view.ViewPager
            android:id="@+id/viewPagerCustom"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@null" />

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:layout_gravity="bottom|center_horizontal">

            <View
                android:id="@+id/separatorCustom"
                android:layout_width="match_parent"
                android:visibility="gone"
                android:layout_height="0.1dp"
                android:background="@android:color/white" />

            <TextView
                android:id="@+id/tvSkipCustom"
                android:layout_width="wrap_content"
                android:layout_height="match_parent"
                android:layout_gravity="bottom"
                android:layout_marginEnd="10dp"
                android:layout_marginRight="10dp"
                android:fontFamily="sans-serif-light"
                android:padding="10dp"
                android:text="skip"
                android:textColor="@android:color/white"
                android:textSize="21sp"
                android:visibility="gone"
                tools:ignore="UnusedAttribute" />

            <com.cleveroad.slidingtutorial.TutorialPageIndicator
                android:id="@+id/indicatorCustom"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="center" />
        </FrameLayout>

    </FrameLayout>

    <Button
        android:id="@+id/btn_continue"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_above="@+id/btn_register"
        android:layout_gravity="bottom|center_horizontal"
        android:layout_marginLeft="20dp"
        android:layout_marginRight="20dp"
        android:layout_marginBottom="@dimen/activity_horizontal_margin"
        android:background="@drawable/bg_yelow_roundedcorners"
        android:text="Continue"
        android:textAllCaps="false"
        android:textColor="@android:color/black"
        android:textSize="@dimen/txt_large" />

    <Button
        android:id="@+id/btn_register"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_marginBottom="@dimen/activity_horizontal_margin"
        android:layout_gravity="bottom|center_horizontal"
        android:layout_marginLeft="20dp"
        android:layout_marginRight="20dp"
        android:background="@drawable/bg_empty_roundedcorners"
        android:text="Register for a free demo"
        android:textAllCaps="false"
        android:textColor="@android:color/white"
        android:textSize="@dimen/txt_large" />
</RelativeLayout>
```

Am using Nexus 5 mobile. My Screen size 4.95-inch, 1920 x 1080 pixel display (445 ppi) . I think  this not a screen size issue, because I tested you sample app. its working properly.

Note : Here I have attached my screenshot. Please find it.

**Comment by Iojjj** [comment]
@SanVakil, I've tried to reproduce this issue on emulator (I don't have Nexus 5) and it's seems to work well. Please check you `provideTutorialOptions()` method. Did you set a renderer for indicator?

``` java
@Override
protected TutorialOptions provideTutorialOptions() {
    return newTutorialOptionsBuilder(getActivity())
            .setUseAutoRemoveTutorialFragment(true)
            .setPagesColors(pagesColors)
            .setPagesCount(TOTAL_PAGES)
            .setIndicatorOptions(IndicatorOptions.newBuilder(getActivity())
                    .setElementSizeRes(R.dimen.indicator_size)
                    .setElementSpacingRes(R.dimen.indicator_spacing)
                    // set default colors for debugging. If you'll pass null as renderer, 
                    // this will display default indicator with specified colors
                    .setElementColorRes(android.R.color.darker_gray)
                    .setSelectedElementColor(Color.LTGRAY)
                    // this is how to set renderer
                    .setRenderer(DrawableRenderer.create(getActivity()))
                    .build())
            .setTutorialPageProvider(mTutorialPageProvider)
            .onSkipClickListener(mOnSkipClickListener)
            .build();
}
```

I will set default indicator color to red for better debugging. If this doesn't help:
1. could you provide your images for indicator?
2. could you provide your `Renderer` implementation?
3. could you provide your `provideTutorialOptions()` method?

**Comment by SanVakil** [comment]
Hi @Iojjj 

Here I have mentioned following details which you asked. Please tell me where is the problem. I tried your sample into my application. i get same issue. can you please help me to solve this issue.

# images for indicator - vec_checkbox_blank_circle_outline.xml
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="24dp"
    android:width="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path android:fillColor="@color/colorPrimaryDark" android:pathData="M12,20A8,8 0 0,1 4,12A8,8 0 0,1 12,4A8,8 0 0,1 20,12A8,8 0 0,1 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" />
</vector>`

# images for indicator - vec_checkbox_fill_circle_outline.xml
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:height="24dp"
        android:width="24dp"
        android:viewportWidth="24"
        android:viewportHeight="24">
<path android:fillColor="@color/colorPrimaryDark" android:pathData="M12,2A10,10 0 0,1 22,12A10,10 0 0,1 12,22A10,10 0 0,1 2,12A10,10 0 0,1 12,2M11,16.5L18,9.5L16.59,8.09L11,13.67L7.91,10.59L6.5,12L11,16.5Z" />
</vector>`

# DrawableRenderer
`public class DrawableRenderer implements Renderer {

    private Drawable mDrawableActive;
    private Drawable mDrawable;

    public static DrawableRenderer create(@NonNull Context context) {
        return new DrawableRenderer(context);
    }

    private DrawableRenderer(@NonNull Context context) {
        mDrawableActive = ContextCompat.getDrawable(context, R.drawable.vec_checkbox_fill_circle_outline);
        mDrawable = ContextCompat.getDrawable(context, R.drawable.vec_checkbox_blank_circle_outline);
    }

    @Override
    public void draw(@NonNull Canvas canvas, @NonNull RectF elementBounds, @NonNull Paint paint, boolean isActive) {
        Drawable drawable = isActive ? mDrawableActive : mDrawable;
        drawable.setBounds((int) elementBounds.left, (int) elementBounds.top,
                (int) elementBounds.right, (int) elementBounds.bottom);
        drawable.draw(canvas);
    }
}`

# provideTutorialOptions
` @Override
    protected TutorialOptions provideTutorialOptions() {
        return newTutorialOptionsBuilder(getActivity())
                .setUseAutoRemoveTutorialFragment(true)
                .setUseInfiniteScroll(true)
                .setPagesColors(pagesColors)
                .setPagesCount(TOTAL_PAGES)
                .setTutorialPageProvider(mTutorialPageOptionsProvider)
                .setIndicatorOptions(IndicatorOptions.newBuilder(getActivity())
                        .setElementSizeRes(R.dimen.indicator_size)
                        .setElementSpacingRes(R.dimen.indicator_spacing)
                        .setElementColorRes(R.color.colorPrimaryDark)
                        .setSelectedElementColor(Color.LTGRAY)
                        .setRenderer(DrawableRenderer.create(getActivity()))
                        .build())
                .setTutorialPageProvider(mTutorialPageProvider)
                .onSkipClickListener(mOnSkipClickListener)
                .build();


    }`

**Comment by Iojjj** [comment]
It works without any problems on my emulator. 
1. It's possible that support library can't properly extract colors for VectorDrawable if this colors were set as references (i.e. `@color/colorPrimaryDark`). Try to set colors as HEX values, this is the only difference between yours and ours vector images. 
2. Check your support library version. I've tested on 24.2.1 and our sample uses 24.2.0. 

If this doesn't help you try to switch to png images rather than using vectors.

**Comment by SanVakil** [comment]
Hi @Iojjj ,

I tried both vectors and png, but not working.

**Comment by Iojjj** [comment]
1. Change background of indicator view and set it's height to some value, for example, 20dp.
2. Check if indicator view is present on screen
3. Use different renderer.
4. Test on other devices.
5. Make sure `draw` method of `Renderer` called with proper `elementBounds` rectangle (i.e. rectangle's width and height greater than zero).
6. Make sure this rectangle is properly located within parent's bounds.
7. Check your logs, maybe you can find something related to bitmap.

That's all I can think about for now. If you have no problems with our sample, then you should check the differences between the sample and your project. Check view hierarchy with DDMS.

**Comment by ghost** [comment]
Hi @Iojjj ,

```
   I identified the issue and fixed. Thanks for your support.
```

   I have configured in AndroidManifest.xml to the <application> the tag android:hardwareAccelerated="false", So its not render properly. Now I changed this option.

   Thanks once again
