### ISSUE TITLE
Enhance ViewPager with "disable paging" functionality

### ISSUE THREAD

**Issue by gajicm93** [Cleveroad/slidingtutorial-android#39]
This is an enhancement. I had to include whole library sources into my project just to add these 2-3 lines..

I don't wanna bother with making forks and pull requests for this tiny change, so I'll just include you my sources here (this should go inside view pager class):

```
private boolean enabled = true;

@Override
public boolean onInterceptTouchEvent(MotionEvent event) {
    if (getAdapter() == null || getAdapter().getCount() == 0 || !enabled) {
        return false;
    }
    return super.onInterceptTouchEvent(event);
}

@Override
public boolean onTouchEvent(MotionEvent ev) {
    if (getAdapter() == null || getAdapter().getCount() == 0 || !enabled) {
        return false;
    }
    return super.onTouchEvent(ev);
}

public void setPagingEnabled(boolean enabled) {
    this.enabled = enabled;
}
```

But all in all, it's an awesome lib guys, congratulations, it would also be awesome to add Direction.TOP and Direction.BOTTOM, just a suggestion.. Cheers.

**Comment by Iojjj** [comment]
Hi @gajicm93,

you don't need to include whole library's source code. The only thing you need is to specify your own XML layout for tutorial fragment where you can put your own implementation of `ViewPager` and pass the id of this layout in `getLayoutResId()` method:

``` java
@Override
protected int getLayoutResId() {
    return R.layout.your_layout;
}
```

We will add new directions and possibly a custom handler for transform items in future releases. Thanks.
