### ISSUE TITLE
Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved.

### ISSUE THREAD

**Issue by OCNYang** [Cleveroad/slidingtutorial-android#42]
Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved.

**Comment by OCNYang** [comment]
when i add "compile 'com.cleveroad:slidingtutorial:1.0.5'", the gradle is error, the error log is "Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved."  I attempt failed many times, I also can't find the reason.

**Comment by Iojjj** [comment]
Hi @OCNYang,

I can't say this error is related to our library. Could you provide some empty sample project with reproduction of this issue?

**Comment by OCNYang** [comment]
I found the root of this error, of course, is not the library error. library depends on " compile 'com.android.support:support-v4:24.2.1' ", but my Android studio2.2 did not download it. 
And Gradle gave me an unrelated error。And when I download the library's demo run only when prompted this error.
