### ISSUE TITLE
Change indicator color?

### ISSUE THREAD

**Issue by broakenmedia** [Cleveroad/slidingtutorial-android#44]
I simply want to change the non-selected and selected colors but i seems i need to set some sort of renderer before it will draw them? If i don't specify one the indicator is now invisible, can i not use the "default" renderer?

**Comment by Iojjj** [comment]
``` JAVA
return newTutorialOptionsBuilder(getContext())
    .setIndicatorOptions(IndicatorOptions.newBuilder(getContext())
        .setElementColor(...)           // non-selected color
        .setSelectedElementColor(...)   // selected color
        .build())
    .build();
```

If you not specified `Renderer` then default circle renderer will be used. You always need to specify `elementColor` and `selectedElementColor`. See [readme](https://github.com/Cleveroad/SlidingTutorial-Android#indicator-view-customization).

**Comment by broakenmedia** [comment]
OK, so that's exactly what i did, except as soon as i do that, the indicator is no longer rendered. See original question. Removing the setIndicatorOptions then brings back the indicator.

**Comment by Iojjj** [comment]
Have you tried to specify one of the default renderers?

``` JAVA
Renderer.Factory.newCircleRenderer()
Renderer.Factory.newSquareRenderer()
```

**Comment by broakenmedia** [comment]
No dice i'm afraid! Still nothing at all.

**Comment by Iojjj** [comment]
There was an issue with `DrawableRenderer` that is mentioned here #36. But I doubt this will help with default circle renderer.

Provide your code of XML layout for tutorial fragment and Java code with `provideTutorialOptions` method.

For now try to implement your own  Renderer and draw  using custom `Paint` object. This is just a quickfix.

``` JAVA

final Paint mElementPaint = ...; // init paint with non-selected color
final Paint mSelectedElementPaint = ...; // init paint with non-selected color

return newTutorialOptionsBuilder(getContext())
    .setIndicatorOptions(IndicatorOptions.newBuilder(getContext())
        .setRenderer(new Renderer() {

                @Override
                public void draw(@NonNull Canvas canvas, @NonNull RectF elementBounds, @NonNull Paint paint, boolean isActive) {
                    float radius = Math.min(elementBounds.width(), elementBounds.height());
                    radius /= 2f;
                    canvas.drawCircle(elementBounds.centerX(), elementBounds.centerY(), radius, isActive ? mSelectedElementPaint : mElementPaint);
                }

        })
        .build())
    .build();

```

**Comment by Iojjj** [comment]
You need to specify the size of elements as well as colors. 

``` java
@Override
protected TutorialOptions provideTutorialOptions() {
    return newTutorialOptionsBuilder(getContext())
            .setIndicatorOptions(IndicatorOptions.newBuilder(getContext())
                    // set this sizes
                    .setElementSizeRes(R.dimen.indicator_size)
                    .setElementSpacingRes(R.dimen.indicator_spacing)
                    .setElementColor(Color.CYAN)
                    .setSelectedElementColor(Color.RED)
                    .build())
            .build();
}
```

Currently the default value for elements and spacing size is zero. That's why it doesn't draw anything.
