### ISSUE TITLE
What happens when they get to the end of the tutorial?

### ISSUE THREAD

**Issue by broakenmedia** [Cleveroad/slidingtutorial-android#45]
On the last slide, how do i get the "Complete" button to appear? There appears to be no way to close the tutorial other than pressing Skip, which is un-intuitive to the user

**Comment by Iojjj** [comment]
You can put `Complete` button anywhere you want: into layout of one (or all) pages, into custom layout of tutorial fragment, into your activity's layout. To hide a tutorial you need to remove a fragment using `FragmentManager`.

**Comment by broakenmedia** [comment]
I don't understand? It would need to be inserted into the actual navigation panel at the bottom, where is the default functionality? It's as though someone forgot to add the ability to actually CLOSE the tutorial? I can of course add this myself but trying to see how we can finish the library so people can actually use it out of the box :)

**Comment by Iojjj** [comment]
Why don't you just change the text of the button at the last slide on your own? You can set a listener and check if user navigated to the last slide and then change the `Skip` text to `Complete`.

**Comment by broakenmedia** [comment]
I did consider that too, however it'd be located on the left hand side, interfering with the established mental model that the left option is "back" as in typical on-boarding screens!

**Comment by Iojjj** [comment]
This minor changes you can add into your app on your own in 5 minutes. This library supports custom layouts so you can customize it in the way you want and place `Skip` or `Complete` button anywhere. 

> where is the default functionality?

There was no such functionality from the beginning.

> It's as though someone forgot to add the ability to actually CLOSE the tutorial?

No one forgot anything. Tutorial fragment can be automatically removed after scrolling to the last, empty page. You can check this behavior by building [one of the first commits](https://github.com/Cleveroad/SlidingTutorial-Android/tree/a9151c258948e08e56bb5aad797316f79c46bb87) and running on your device. Such functionality still present in latest build, but you need to enable it by doing [this](https://github.com/Cleveroad/SlidingTutorial-Android#auto-remove-tutorialfragment---scroll-from-last-tutorial-page-to-your-content) and disabling infinite scroll. This was the default behavior from the beginning. And it's very obvious that if you want to close tutorial you need just to remove the fragment.

In my opinion when you use some libraries in your app and you need to implement something that library not supports, you can first check if it's possible to do that without modification of sources. Our sample with custom layout [[#1](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/sample/src/main/java/com/cleveroad/slidingtutorial/sample/CustomTutorialFragment.java), [#2](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/sample/src/main/res/layout/custom_tutorial_layout_ids_example.xml)] shows you that you can specify any layout you want, the only requirement is that `ViewPager`, `PagerIndicator` and skip button must be present in layout.

If you have your vision of how Tutorial should work, what other controls should be displayed and at what point of time, please share it with us. Maybe you have some good ideas that we can implement in this library.

Thanks for discussion.
