### ISSUE TITLE
skipBar color and position

### ISSUE THREAD

**Issue by Pawantag** [Cleveroad/slidingtutorial-android#48]
how to change skip bar background color and its position

**Comment by Iojjj** [comment]
Hi @Pawantag,

you can specify custom layout for tutorial fragment. There you can do whatever you want. This is the only way to customize skip bar.

See
* [Custom layouts in readme](https://github.com/Cleveroad/SlidingTutorial-Android/wiki/Quick-Start#custom-tutorial-layout)
* [Our custom layout sample](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/sample/src/main/res/layout/custom_tutorial_layout.xml)
