### ISSUE TITLE
TutorialSupportFragment.newInstance returns TutorialFragment instead of TutorialSupportFragment

### ISSUE THREAD

**Issue by smabbasdev** [Cleveroad/slidingtutorial-android#50]
`final TutorialSupportFragment tutorialFragment = TutorialSupportFragment.newInstance(tutorialOptions);`

The compiler throws up an error when using this code

**Comment by ValeryGes** [comment]
Hi @smabbas1234, Thank you for your feedback, we will fix this issue in next release. For now you can fork library and fix it by yourself. For this you need to open [TutorialSupportFragment](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/TutorialSupportFragment.java#L286) class and replace **TutorialFragment** with **TutorialSupportFragment**.

With best regards, Cleveroad team.

**Comment by smabbasdev** [comment]
Thanks for the immediate response. You guys are doing a great job

**Comment by ValeryGes** [comment]
@smabbas1234, this issue fixed in version 1.0.7 

With best regards, Cleveroad team.
