### ISSUE TITLE
addOnTutorialPageChangeListener giving a nullPointerException

### ISSUE THREAD

**Issue by srujanb** [Cleveroad/slidingtutorial-android#53]
I have implemented this tutorial directly in my tutorial activity using this code:

    private void replaceTutorialFragment() {
        final IndicatorOptions indicatorOptions = IndicatorOptions.newBuilder(this)
                .build();
        final TutorialOptions tutorialOptions = TutorialFragment.newTutorialOptionsBuilder(this)
                .setUseAutoRemoveTutorialFragment(false)
                .setUseInfiniteScroll(false)
                .setPagesColors(mPagesColors)
                .setPagesCount(TOTAL_PAGES)
                .setIndicatorOptions(indicatorOptions)
                .setTutorialPageProvider(new TutorialPagesProvider())
                .setOnSkipClickListener(new OnSkipClickListener(this))
                .build();
        final TutorialFragment tutorialFragment = TutorialFragment.newInstance(tutorialOptions);
        getFragmentManager()
                .beginTransaction()
                .replace(R.id.container, tutorialFragment)
                .commit();    
    }

Just like you've done in your MainActivity.java inside the Sample dir.

I also added the following code in the above block:

    tutorialFragment.addOnTutorialPageChangeListener(new OnTutorialPageChangeListener() {
            @Override
            public void onPageChanged(int position) {
                Log.d("TAGG","Position: " + position);
            }
        });

to listen to page changes but this is giving me a NullPointerException.

    Caused by: java.lang.NullPointerException
        at com.cleveroad.slidingtutorial.TutorialFragment.addOnTutorialPageChangeListener(TutorialFragment.java:199)
        at spoonmoon.com.m******21.TutorialActivity.replaceTutorialFragment(TutorialActivity.java:73)

**Also to mention. Without the `pageChangeListener` the tutorial is working fine.** 

Am I doing anything wrong?

**Comment by Iojjj** [comment]
@srujan7 

Currently you can call `TutorialFragment.addOnTutorialPageChangeListener` only after `onCreate` method of `TutorialFragment` was called. We'll check it and figure out if it can be fixed.

**Comment by srujanb** [comment]
So is there any simple way I can listen to page changes? @Iojjj

**Comment by Iojjj** [comment]
See [Custom Tutorial Layout](https://github.com/Cleveroad/SlidingTutorial-Android/wiki/Quick-Start#custom-tutorial-layout), but provide our xml layout. This will allow you to get an access to ViewPager and set listener on it.

**Comment by srujanb** [comment]
I've done a very stupid workaround for now but it is working anyways. I have added the `OnPageChangeListener` at a delay of 500 millis in background and am handling any exceptions if generated. Will get back and improve whenever gets time. 

I'd love to see amendments to be able to add `OnPageChangeListener` before `onCreate`.

**Comment by ValeryGes** [comment]
Hi @srujan7, this issue fixed in version 1.0.8. 
Now you can add OnPageChangeListener before onCreate.

With best regards, Cleveroad team.
