### ISSUE TITLE
TutorialPageIndicator is not show

### ISSUE THREAD

**Issue by OCNYang** [Cleveroad/slidingtutorial-android#56]
<com.cleveroad.slidingtutorial.TutorialPageIndicator
            android:id="@+id/indicator"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center"/>
OR
 <com.cleveroad.slidingtutorial.TutorialPageIndicator
            android:id="@+id/indicator"
            android:layout_width="match_parent"
            android:layout_height="20dp"
            android:layout_gravity="center"/>

Setting:
newTutorialOptionsBuilder(getContext())
                .setUseInfiniteScroll(true)
                .setPagesColors(pagesColors)
                .setPagesCount(TOTAL_PAGES)
                .setTutorialPageProvider(mTutorialPageOptionsProvider)
                .setIndicatorOptions(IndicatorOptions.newBuilder(getContext())
                        .setElementSizeRes(R.dimen.indicator_size)
                        .setElementSpacingRes(R.dimen.indicator_spacing)
                        .setElementColorRes(android.R.color.darker_gray)
                        .setSelectedElementColor(Color.LTGRAY)
                        .setRenderer(DrawableRenderer.create(getActivity()))
                        .build())
                .onSkipClickListener(mOnSkipClickListener)
                //.setTutorialPageProvider(mTutorialPageProvider)
                .build();

I dont know why ,Other code is the same as Demo, but it is not shown. I feel its height has been 0dp, so it is not shown

**Comment by OCNYang** [comment]
This problem bothered me for a long time, and I spent half a day in order to find the cause. I tried all the possible problems. Now finally found，
The reason is:
```
<application
        ......
        android:hardwareAccelerated="false"
       .....
```

The This is a hard to think of the reasons, and hope that the author can declare this issue in the usage, since the other users to remind.

**Comment by Iojjj** [comment]
@OCNYang,

we'll add this to readme. This issue was already discussed in #36.
