### ISSUE TITLE
Add findViewById in fragment method of library

### ISSUE THREAD

**Issue by fabian7593** [Cleveroad/slidingtutorial-android#57]
Hello, I want to call the findViewById of an UI Component of my fragment xml... 
But the tutorialOptions instance return getActivity and getView in null... 
And I dont have the possibillity of  call the findViewById. 
If you need more information for understand the problem please tell me...

I hope that you can help me.

Thanks.

Example
```
 public void replaceTutorialFragment() {
        final IndicatorOptions indicatorOptions = IndicatorOptions.newBuilder(this)
                .build();
        final TutorialOptions tutorialOptions = TutorialFragment.newTutorialOptionsBuilder(this)
                .setUseAutoRemoveTutorialFragment(true)
                .setUseInfiniteScroll(true)
                .setPagesColors(mPagesColors)
                .setPagesCount(TOTAL_PAGES)
                .setIndicatorOptions(indicatorOptions)
                .setTutorialPageProvider(new TutorialPagesProvider())
                .setOnSkipClickListener(new OnSkipClickListener(this))
                .build();
        final TutorialFragment tutorialFragment = TutorialFragment.newInstance(tutorialOptions);
        getFragmentManager()
                .beginTransaction()
                .replace(R.id.container, tutorialFragment)
                .commit();



//This is the test, but tutorialOptions return any options in null
(ImageView) imgView = (ImageView)tutorialOptions.getActivity().findViewById(R.id.img_view_test);

if(imgView != null){

} 
}
```

**Comment by Iojjj** [comment]
You should learn basics of using of fragments. When you call `getFragmentManager().commit()`, it posts operation to queue so fragment will be added to screen asynchronously. When you then try to find an image view, it's not added to view hierarchy yet. See Javadoc of `commit` method: 

`Schedules a commit of this transaction.  The commit does not happen immediately; it will be scheduled as work on the main thread to be done the next time that thread is ready.`

But you can use `commitNow` method instead.

Also note:

1. **Do not ever use views from fragments in other Android components** (i.e. activities, other fragments). Only fragment that displays that view must find and use it. So if you need to interact with image view, do it in the fragment.
2. `TutorialOptions` instance used by this library's internal components. You don't need to use it at all. Just construct it and pass to `TutorialFragment`.

**Comment by Iojjj** [comment]
According to the title of this issue `Add findViewById in fragment method of library`:

It's you who decide which fragments to use. If you need to interact with views of your fragment, then create your own fragment and extend it from `PageFragment`. There you can manipulate fragment's views. Then you should use `TutorialPageProvider` instead `TutorialPageOptionsProvider`. See [Configure Tutorial Pages: Via TutorialPageProvider](https://github.com/Cleveroad/SlidingTutorial-Android/wiki/Configure-Tutorial-Pages#via-tutorialpageprovider).

**Comment by fabian7593** [comment]
Thanks for your response, I try to fix this
