### ISSUE TITLE
Custom Transformation and animation example

### ISSUE THREAD

**Issue by sandeshlasnapure** [Cleveroad/slidingtutorial-android#58]
Can you add some example for custom transformation and animation?

**Comment by ValeryGes** [comment]
Hi, @sandeshlasnapure,

Sorry for late answer and thank you for using our library. 
Can you give us some description of your meaning of custom animation?

With best regards, Cleveroad team.

**Comment by sandeshlasnapure** [comment]
I need to add custom animation for each element like alpha and more, so how can I add that . You are just providing some basic animations.
And one another bug I found in library is when we scroll the page and left it in half way, it will scroll back reverse +1 position.
lets say am on page 1, I am scrolling to 2 and 3, while scrolling from page 3 to 4, lift the touch and page will be reversed to 1, but should go to page 2.
Let me know if you need more info on this. Thanks

1=>2=>**3**(3 reached at 50% of screen)=>**4**
**1<=3**(reverse scroll)

**Comment by VadimHalimendikCr** [comment]
Hello! We fixed this bug in the latest version of this library.
Best regards Cleveroad team.
