### ISSUE TITLE
What is the point of Direction.LEFT_TO_RIGHT?

### ISSUE THREAD

**Issue by wuhuanyu** [Cleveroad/slidingtutorial-android#64]
Sorry for stupid question, but in the sample app provided I change `Direction.LEFT_TO_RIGHT` to `Direction.RIGHT_TO_LEFT`, I found nothing changed. Is there any subtle differences between the two?

**Comment by VadimHalimendikCr** [comment]
Hello! We fixed this bug in the latest version of this library.
Best regards Cleveroad team.
