### ISSUE TITLE
Hidding 'Skip' button

### ISSUE THREAD

**Issue by eduochieng** [Cleveroad/slidingtutorial-android#65]
Is there a way to hide the skip button? My app doesn't need it. Thanks for the awesome lib!

**Comment by mohkamfer** [comment]
TextView skip = findViewById(R.id.tvSkip);
skip.setVisibility(View.GONE);

EDIT: If you can't get a reference because it wasn't inflated yet, you gotta .post(Runnable) your snippet.

**Comment by VadimHalimendikCr** [comment]
Hide the skip button was integrated in version 1.0.9.
With best regards Cleveroad team.
