### ISSUE TITLE
Error:(2) Attribute "radius" has already been defined

### ISSUE THREAD

**Issue by semmiverian** [Cleveroad/slidingtutorial-android#7]
First of all thanks for creating this awesome stuff 
i encountered this error while trying to compile 
Error:(2) Attribute "radius" has already been defined 

i already google and it's looks like another library i used already defined that attribute radius. 
is there anything i could do to fix that? thanks in advance

**Comment by Iojjj** [comment]
Hi there.

v.0.9.4 is released. All attributes where renamed, prefix 'st_' added. Update library version in your project and rename all attributes used in XML. See migration steps in [readme](/Cleveroad/slidingtutorial-android/blob/master/README.md#migrations-from-v093-to-v094) for more info.
