### ISSUE TITLE
Imposibble to use with support fragment manager

### ISSUE THREAD

**Issue by tolgaytoklar** [Cleveroad/slidingtutorial-android#71]
![ekran resmi 2019-01-02 12 23 00](https://user-images.githubusercontent.com/767253/50586118-37252380-0e89-11e9-9ddf-7b610c2e335a.png)

Because `TutorialSupportFragment.newInstance` is returning `TutorialFragment` not `TutorialSupportFragment`

**Comment by VadimHalimendikCr** [comment]
Hi @tolgaytoklar, we are trying to reproduce the problem, but cannot. Have you tried to clear a project or invalidate a cache? If so, tell me what version of the library you are using.
![image](https://user-images.githubusercontent.com/39762210/50956782-3c0b5800-14c5-11e9-8fc0-36e165fd7bc0.png)
