### ISSUE TITLE
how to let the circleIndicator‘s little point through the background of fragment？

### ISSUE THREAD

**Issue by Andecy** [Cleveroad/slidingtutorial-android#9]
thank you!

**Comment by Andecy** [comment]
and hide the line between indicator and pager

**Comment by Iojjj** [comment]
Hi.

I can't understand your first question. Please, explain it a little more.

About second one: currently it's not possible. We'll add an ability to get views of fragment in next release.

**Comment by Andecy** [comment]
@Iojjj 

thank for your reply, 
enn,it like them,when we change page1 to page2(total 4 page assum),the white bobble will from first hole go to second,I hope the bobble can through "underground" but "ground"

this is the pic about first quesion,thank you!
http://my.poco.cn/lastphoto_v2-htx-id-5059889-user_id-178820858-p-0.xhtml

**Comment by Iojjj** [comment]
Currently we're using CircleViewPagerIndicator from [Jake Wharton's library](https://github.com/JakeWharton/ViewPagerIndicator) with small modifications for supporting infinite scrolling. Such behavior of indicator showed on picture isn't supported by this indicator. 

You need to create your own view pager indicator to achieve such behavior. We'll add an ability to set custom indicator in next release.

**Comment by Andecy** [comment]
@thank you!

**Comment by Andecy** [comment]
@Iojjj thank you!

**Comment by Iojjj** [comment]
Added getters in fragment in new version 0.9.5. You can get separator view with **getSeparator()** method and hide it.

**Comment by davinctor** [comment]
hi @Andecy, thanks for your questions.

To set custom **ViewPager** indicator you should do next steps:
- Extend your tutorial fragment from the [TutorialFragment](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/TutorialFragment.java) or  [TutorialSupportFragment](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/TutorialSupportFragment.java).
- Provide your xml layout file:

``` java
public class YourTutorialFragment extends from TutorialSupportFragment {
    @Override
    protected int getLayoutResId() {
        return R.id.your_layout;
    }

    @Override
    protected int getViewPagerResId() {
        return R.id.viewPager;
    }

    @Override
    protected int getIndicatorResId() {
        return R.id.indicatorView;
    }

    @IdRes
    protected int getButtonSkipResId() {
        return R.id.buttonSkip;
    }

    @IdRes
    protected int getSeparatorResId() {
        return R.id.separatorView;
    }
}
```
- Your xml must have similar elements structure like this one:

``` xml
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.view.ViewPager
        android:id="@+id/viewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_gravity="bottom|center_horizontal">

        <View
            android:id="@+id/separator"
            android:layout_width="match_parent"
            android:layout_height="0.1dp"
            android:background="@android:color/white"/>

        <TextView
            android:id="@+id/tvSkip"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:text="@string/st_skip""/>

        <!-- Here your custom indicator view -->
        <YourIndicatorView
           android:id="@+id/indicatorView"
            />

    </FrameLayout>

</FrameLayout>
```
-  Inside your **YourTutorialFragment** you need to implement [OnTutorialPageChangeListener](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/OnTutorialPageChangeListener.java) and update **YourIndicatorView** when event came:

``` java
public class CustomTutorialFragment extends TutorialSupportFragment
        implements OnTutorialPageChangeListener {

    private static final int TOTAL_PAGES = 6;

    private YourIndicatorView indicatorView;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View root = super.onCreateView(inflater, container, savedInstanceState);
        indicatorView = (YourIndicatorView) getPagerIndicator();
        indicatorView.setTotalPagesCount(TOTAL_PAGES);
        return root;
    }

    @Override
    public void onPageChanged(int position) {
        indicatorView.setCurrentElement(position);
    }
}
```

#### Or you could easily customize the [TutorialPageIndicator](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/TutorialPageIndicator.java) via [IndicatorOptions](https://github.com/Cleveroad/SlidingTutorial-Android/blob/master/lib/src/main/java/com/cleveroad/slidingtutorial/IndicatorOptions.java). **See** the [issue](https://github.com/Cleveroad/SlidingTutorial-Android/issues/10#issuecomment-243117273) about it.
